[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        Content-Security-Policy = "default-src 'self'; frame-src 'self'; frame-ancestors 'self' api-glitchspeech.herokuapp.com/; form-action 'self' api-glitchspeech.herokuapp.com/;"
        X-XSS-Protection = "0"
        X-Content-Type-Options = "nosniff"
