[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; form-action 'self';"
        Cache-Control = "Cache-Control: no-cache, no-store, must-revalidate"
        X-XSS-Protection = "0"
        X-Content-Type-Options = "nosniff"
